services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped  # Auto-restart unless manually stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - .:/app
    environment:
      - SERVER_URL=http://server:5000
      - CSV_FILE=/app/ip_addresses.csv
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped